---

title: "Percona Server for MongoDB: CPU and I/O scalability for
WiredTiger and RocksDB"
author: "Percona Lab"
generated on:`r format(Sys.Date(), "%B %d, %Y")`
output:
  md_document:
    variant: markdown_github

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(ggthemes)
library(reshape2)
library(knitr)
library(plyr)

label_custom <- function(variable, value) {
    if (variable=="version") {
       return(sub("upstream","M",sub("psmdb","P",value)))
    } else if (variable=="Group.4") { 
	return("engine")
    } else if (variable=="Group.1") {
        return("threads")
    } else if (variable=="Group.2") {
        return("memory")
    }else {
      return (as.character(value))
    }
}

memScalability <- read.csv("../alldata.csv", header=T)
attach(memScalability)
memScalabilityAggregated <- aggregate(memScalability$tps, by=list(user_provided_threads, memory, workload, engine),FUN=function(x) quantile(x, probs=0.99))
detach(memScalability)
dstat <- read.csv("../dstat.csv", header=T)

nothreads <- c(14,28,56,84,112,140)
memorySizes <- c(4,12,20,28,36,44,52,60,68,76,84,92,100,108,116,124,132,140,148,156,164,172,180,188,196)
#filesystems <- c("ext4","xfs")
#configurations <- c("rocks0","wt0","wt1","wt2")

```
# Percona Server for MongoDB 3.2.4-1.rc2 - I/O scalability 

## Setup

* Setup information pending 

## Memory Scalability tests

```{r mem, fig.width=36, fig.height=16, warning=FALSE, echo=FALSE}

attach(memScalabilityAggregated)
print(
    ggplot(memScalabilityAggregated, aes(x=as.factor(Group.1),y=as.numeric(x),color=as.factor(Group.2),group=Group.2)) +
    facet_grid(. ~ Group.4, labeller = label_both) + geom_line() + geom_point(size=4) +
    labs(x="threads",y="tps",title=".99 quantile throughput per threads and memory") + 
    scale_color_tableau(name="memory") +
    scale_y_continuous(breaks=extended_range_breaks()(rbind(0,memScalability$x)),labels = scales::comma)+theme(axis.text.x  = element_text(angle=45, vjust=0.5))+theme_bw() + theme(panel.grid = element_line(colour="#010101",size=1), panel.background = element_rect(colour="#000000"), plot.background = element_rect(colour="#000000"), strip.background = element_rect(colour="#010101"), text=element_text(size=50), strip.text=element_text(size=60)) 
)

detach(memScalabilityAggregated)

for (wl in c("OLTP-RO")) { 
    data <- subset(memScalability, workload == wl) 
    p <- ggplot(data, aes(x=ts, y=tps, color=as.factor(engine))) +
        facet_grid(user_provided_threads ~ memory) +
        geom_jitter(size=8,width=0.2,height=0.2) +
        theme_bw() +
        labs(x="time (secs)",y="throughput (tps)",title=paste("Throughput per
        engine and threads (", wl, ")")) + expand_limits(x=0,y=0) +
        scale_y_continuous(breaks=extended_range_breaks()(rbind(0,data$tps))) +
        #scale_x_continuous(breaks=c(maxtime)) + 
        theme(panel.grid = element_line(colour="#010101",size=1),
        panel.background = element_rect(colour="#000000"),
        plot.background = element_rect(colour="#000000"),
        strip.background = element_rect(colour="#010101"),
        text=element_text(size=50),
        strip.text=element_text(size=60))
    print(p)
}
```

## Disk ops 

```{r disk, fig.width=36, fig.height=16, warning=FALSE, echo=FALSE} 

for (t in nothreads) {
    for (m in memorySizes) {
        data <- subset(dstat, threads == t & memory == m)
        attach(data)
        p <- ggplot(data, aes(x=i, y=dsk.total, color=as.factor(engine))) +
            #facet_grid(configuration ~ .) +
            geom_jitter(size=8,width=0.2,height=0.2) +
            theme_bw() +
            labs(x="seq",y="dsk.total",title=paste("dstat/dsk.total per
            engine (", t, " threads,", ",", m,"GB)")) + expand_limits(x=0,y=0) +
            #scale_y_discrete(breaks=extended_range_breaks()(rbind(0,dstatData$dsk.total))) +
            theme(panel.grid = element_line(colour="#010101",size=1),
            panel.background = element_rect(colour="#000000"),
            plot.background = element_rect(colour="#000000"),
            strip.background = element_rect(colour="#010101"),
            text=element_text(size=50),
            strip.text=element_text(size=60))
        print(p)        
        detach(data)
    } # for m in ...
} # for t in ...

``` 

