---

title: "Percona Server for MongoDB 3.2.7: WiredTiger vs InMemory linkbench performance"

author: "Percona Lab"
generated on:`r format(Sys.Date(), "%B %d, %Y")`
output:
  md_document:
    variant: markdown_github

---

```{r setup, include=FALSE, warning=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(ggthemes)
library(reshape2)
library(knitr)
library(plyr)

label_custom <- function(variable, value) {
    if (variable=="engine") {
       return (ifelse(value=="inmemory","inMemory","wiredTiger"))
    } else {
      return (as.character(value))
    }
}

data <- read.csv("../../raw/linkbenchX/linkbench.csv", header=T)
#data <- subset(data, ts <= 1500) # to work around the drop in tps near the end of the benchmark

```

# Percona Server for MongoDB 3.2.7-1.1 - WiredTiger vs InMemory linkbench performance

## Setup

* WiredTiger: psmdb 3.2.7-1.1 
* InMemory: built from source, v3.2 percona-server-mongodb branch
* linkbenchX with default workload, 100 threads, 5000000 nodes, 22650508 links (8GB datadir) 
* inMemorySizeGB / wiredTigerCacheSizeGB set to 32GB


```{r short, fig.width=36, fig.height=16, warning=FALSE, echo=FALSE}
        attach(data)
        p <- ggplot(data, aes(x=ts, y=tps, color=as.factor(engine))) +
            scale_color_discrete(name = "Engine") +
            geom_jitter(size=8,width=0.2,height=0.2) +
            theme_bw () + theme(text = element_text(size=60)) + 
            labs(x="time (secs)", y="throughput (tps)", title=paste("WiredTiger vs InMemory throughput - linkbench")) +
            #scale_y_continuous(breaks=extended_range_breaks()(rbind(0,data$tps))) +
            scale_y_continuous() +
            theme(panel.grid = element_line(colour="#010101",size=1),
            panel.background = element_rect(colour="#000000"),
            plot.background = element_rect(colour="#000000"),
            strip.background = element_rect(colour="#010101"))
            print(p) 




```


