---
title: "local PK"
author: "None"
date: "March 17, 2016"
--output: html_document
output:
  md_document:
    variant: markdown_github

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(ggthemes)
library(reshape2)
library(knitr)

tm<-theme(legend.position="bottom",
          text=element_text(family="Georgia"),
          strip.background = element_rect(colour="red", fill="#CCCCFF"))

guides(colour = guide_legend(override.aes = list(size=4)))

data = read.table("../summary.csv",sep=",",header=F)
data1=subset(data,V1>100)
attach(data1)
aggdata <-aggregate(data1, by=list(V4,V5),FUN=mean, na.rm=TRUE)
```
# Percona Server 5.7 - proxy overhead

## Setup

* Client (sysbench) and server are on different servers, connected via 10Gb network. 
* CPU: 56 logical CPU threads servers Intel(R) Xeon(R) CPU E5-2683 v3 @ 2.00GHz
* sysbench 10 tables x 10mln rows, pareto distribution
* OS: Ubuntu 15.10 (Wily Werewolf)
* Kernel 4.2.0-30-generic

```{r test, eval=FALSE, fig.height=8, fig.width=10, warning=FALSE, include=FALSE}
ss=subset(aggdata)

m <- ggplot(ss, aes(x=as.factor(Group.2),y=as.numeric(V2),color=as.factor(Group.1),group=Group.1))
m+geom_line()+geom_point(size=1)+labs(x="Threads",y="Throughput,tps",title="sysbench OLTP read-only")+scale_color_tableau(name="Version")+scale_y_continuous(breaks=seq(0, 22000, 1000),labels = scales::comma)+theme(axis.text.x  = element_text(angle=45, vjust=0.5))+tm
```
```{r perthread, eval=FALSE, fig.height=8, fig.width=10, warning=FALSE, include=FALSE}
ss=subset(aggdata)
ss$rel<-ss$V2/ss$V5
m <- ggplot(ss, aes(x=as.factor(Group.2),y=as.numeric(rel),fill=as.factor(Group.1),group=Group.1))
m+geom_bar(stat = "identity",position = "dodge")+labs(x="Threads",y="Throughput,tps",title="sysbench OLTP read-only")+scale_fill_tableau(name="Version")+scale_y_continuous(breaks=seq(0, 1000, 100),labels = scales::comma)+theme(axis.text.x  = element_text(angle=45, vjust=0.5))+tm
```
```{r test2, eval=FALSE, fig.height=8, fig.width=10, warning=FALSE, include=FALSE}
ss=subset(aggdata)

m <- ggplot(ss, aes(x=as.factor(Group.2),y=as.numeric(V3),color=as.factor(Group.1),group=Group.1))
m+geom_line()+geom_point(size=1)+labs(x="Threads",y="Throughput,tps",title="sysbench read-only")+scale_color_tableau(name="Version")+scale_y_log10(breaks=c(.001,.01,0.05,.1,.5,1,10,100,250,500,1000),limits = c(.01,1000))
#+theme(axis.text.x  = element_text(angle=45, vjust=0.5))+tm
```

## Results under OLTP RO pareto

* MySQL 5.7

```{r versions, echo=FALSE, warning=FALSE,fig.width=10, fig.height=8}
ss=subset(aggdata,(Group.2<=1000) )
#ss=subset(aggdata)

m <- ggplot(ss, 
            aes(x=as.factor(Group.2),y=as.numeric(V2),color=as.factor(Group.1),group=Group.1))
m+geom_line()+geom_point(size=1)+labs(x="Threads",y="Throughput, tps",title="sysbench OLTP RO")+scale_color_tableau(name="Version")+scale_y_continuous(breaks=seq(0, 22000, 1000),labels = scales::comma)+theme(axis.text.x  = element_text(angle=45, vjust=0.5))+tm
```

### Relative performance 

* base value: MySQL 5.7

```{r perf-schema-relative, echo=FALSE, fig.height=8, fig.width=10, message=FALSE, warning=FALSE}
Res<-data.frame(aggdata$Group.1, aggdata$Group.2, aggdata$V2)

wide_format <- dcast(subset(Res), aggdata.Group.2 ~ aggdata.Group.1)


ss=subset(aggdata,(Group.2<=1000))
#ss=subset(aggdata)
wide_format$`MySQL 55` = wide_format$`mysql55.long`/wide_format$`mysql57.long`
wide_format$`MySQL 56 (itc 64)` = wide_format$`mysql56.itc64.long`/wide_format$`mysql57.long`

dat_m <- melt(subset(wide_format), id.vars = "aggdata.Group.2", measure.vars=c("MySQL 55","MySQL 56 (itc 64)"))

m <- ggplot(dat_m, 
            aes(x=as.factor(aggdata.Group.2),y=as.numeric(value),group=variable))
m+geom_bar(stat = "identity",position = "dodge",aes(fill = as.factor(variable)))+geom_hline(yintercept=1)+geom_text(aes(label=format(value, digits=2, nsmall=2), 
                hjust=1), 
            position = position_dodge(width=0.9),size=3,angle = 90)+labs(x="Threads",y="relative performance",title="sysbench OLTP RO")+scale_fill_tableau(name="Version")+scale_y_continuous(breaks=seq(0, 1.5, 0.1),labels = scales::comma)+theme(axis.text.x  = element_text(angle=45, vjust=0.5))+tm
```
